name: Deploy

on: [push, pull_request]

jobs:
  deploy_linux:
    name: Deploy on Ubuntu 18.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install main dependencies
      run: sudo apt-get install build-essential gcc-8 g++8 cmake make lcov gcovr

    - name: Install third-party dependencies
      run: sudo apt-get install doxygen graphviz texlive-latex-base texlive-latex-recommended texlive-fonts-recommended
      
  deploy_win:
    name: Deploy on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
